/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AuthenticatedTransaccionesRouteImport } from './routes/_authenticated/transacciones'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings/team'
import { Route as AuthenticatedSettingsImportRouteImport } from './routes/_authenticated/settings/import'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsFixedCostsRouteImport } from './routes/_authenticated/settings/fixed-costs'
import { Route as AuthenticatedSettingsCatalogRouteImport } from './routes/_authenticated/settings/catalog'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransaccionesRoute =
  AuthenticatedTransaccionesRouteImport.update({
    id: '/transacciones',
    path: '/transacciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsImportRoute =
  AuthenticatedSettingsImportRouteImport.update({
    id: '/settings/import',
    path: '/settings/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsFixedCostsRoute =
  AuthenticatedSettingsFixedCostsRouteImport.update({
    id: '/settings/fixed-costs',
    path: '/settings/fixed-costs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCatalogRoute =
  AuthenticatedSettingsCatalogRouteImport.update({
    id: '/settings/catalog',
    path: '/settings/catalog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/transacciones': typeof AuthenticatedTransaccionesRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/settings/fixed-costs': typeof AuthenticatedSettingsFixedCostsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/transacciones': typeof AuthenticatedTransaccionesRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/settings/fixed-costs': typeof AuthenticatedSettingsFixedCostsRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/import': typeof AuthenticatedSettingsImportRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/transacciones': typeof AuthenticatedTransaccionesRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/_authenticated/settings/catalog': typeof AuthenticatedSettingsCatalogRoute
  '/_authenticated/settings/fixed-costs': typeof AuthenticatedSettingsFixedCostsRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/import': typeof AuthenticatedSettingsImportRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categorias'
    | '/dashboard'
    | '/transacciones'
    | '/accept-invite/$token'
    | '/settings/catalog'
    | '/settings/fixed-costs'
    | '/settings/general'
    | '/settings/import'
    | '/settings/team'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categorias'
    | '/dashboard'
    | '/transacciones'
    | '/accept-invite/$token'
    | '/settings/catalog'
    | '/settings/fixed-costs'
    | '/settings/general'
    | '/settings/import'
    | '/settings/team'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/categorias'
    | '/_authenticated/dashboard'
    | '/_authenticated/transacciones'
    | '/accept-invite/$token'
    | '/_authenticated/settings/catalog'
    | '/_authenticated/settings/fixed-costs'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/import'
    | '/_authenticated/settings/team'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transacciones': {
      id: '/_authenticated/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof AuthenticatedTransaccionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/import': {
      id: '/_authenticated/settings/import'
      path: '/settings/import'
      fullPath: '/settings/import'
      preLoaderRoute: typeof AuthenticatedSettingsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/fixed-costs': {
      id: '/_authenticated/settings/fixed-costs'
      path: '/settings/fixed-costs'
      fullPath: '/settings/fixed-costs'
      preLoaderRoute: typeof AuthenticatedSettingsFixedCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/catalog': {
      id: '/_authenticated/settings/catalog'
      path: '/settings/catalog'
      fullPath: '/settings/catalog'
      preLoaderRoute: typeof AuthenticatedSettingsCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTransaccionesRoute: typeof AuthenticatedTransaccionesRoute
  AuthenticatedSettingsCatalogRoute: typeof AuthenticatedSettingsCatalogRoute
  AuthenticatedSettingsFixedCostsRoute: typeof AuthenticatedSettingsFixedCostsRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsImportRoute: typeof AuthenticatedSettingsImportRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTransaccionesRoute: AuthenticatedTransaccionesRoute,
  AuthenticatedSettingsCatalogRoute: AuthenticatedSettingsCatalogRoute,
  AuthenticatedSettingsFixedCostsRoute: AuthenticatedSettingsFixedCostsRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsImportRoute: AuthenticatedSettingsImportRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
